spring.datasource.url=jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
spring.datasource.username=${postgres.username}
spring.datasource.password=${postgres.password}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false